### ISSUE TITLE
"Signed out successfully" notice appears when signing in on InSTEDD Platform

### ISSUE THREAD

**Issue by pmallol** [instedd/alto_guisso#3]
Found in version fc884822567c8a7f44cebf49894fd8e485cbfa77
1. Go to Resource Map (version 2.14-pre2, also happens with mBuilder v1.1-63-g6224c7d and Verboice v2.3.7-4-gc92444b)
2. Click on 'Log in' 
3. Click 'Sign in with Google' or sign in with email and password
4. After being redirected to Resource Map, click on the user's email and in the drop-down menu click 'Sign out'
5. Click 'Log in' again

Expected: when you sign out a notice that reads "Signed out successfully" appears in the Resource Map app and when you click 'Log in' for the second time you get redirected to the InSTEDD Platform.

Obtained:  when you click 'Log in' for the second time you get redirected to the InSTEDD Platform and another "Signed out successfully" notice appears.

![screen shot 2014-11-06 at 3 47 23 pm 2](https://cloud.githubusercontent.com/assets/9214460/4941708/7a344c56-65e5-11e4-8e05-d68b7689d37d.png)

**Comment by jkicillof** [comment]
I think somewhere there is a doc with that specification for instedd platform where says that we should use always "Log in" and "Create Account" because "Sing up" and "Sign in" could result confusing
